apiVersion: 1
deleteDatasources:
  - name: grafana-postgresql-datasource
    orgId: 1
  - name: grafana-postgresql
    orgId: 1
datasources:
  - name: Postgres (boreas_db)
    uid: boreas_postgres
    type: postgres
    access: proxy
    url: db:5432
    database: boreas_db
    isDefault: false
    user: boreas_user
    secureJsonData:
      password: boreas_password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true
