global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'django'
    metrics_path: /metrics/
    static_configs:
      - targets: ['web:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'anomaly_detector'
    static_configs:
      - targets: ['anomaly_detector:2112']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
